[build]
  command = "npm run build"
  publish = "dist"

# ✅ Redirect SPA routes to index.html (fix 404 on /admin/dashboard reload)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Allow backend cookies for login sessions (Netlify ➞ Render)
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Credentials = "true"
[[redirects]]
  from = "/api/*"
  to = "https://backend-5hej.onrender.com/:splat"
  status = 200
